#!/usr/bin/env bash

while :
do

  find ~/Chia2/Plots/. -size +4G -name "*plot" -name "plot*" -exec mv -nv {} ./run/user/1000/gvfs/dav:host=webdav.hidrive.ionos.com,ssl=true/public/ \;
  echo "checked at:      $(date)"
  
  sleep 10s

done
